# Generated by Django 6.0.1 on 2026-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_genrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetials',
            name='description',
            field=models.JSONField(),
        ),
    ]
